{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "SII API",
    "description": "Documentación para la api del sistema de información integral del Tecnológico Nacional de México campus San Juan del Río",
    "contact": {}
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Local server"
    }
  ],
  "basePath": "/",
  "securityDefinitions": {},
  "schemes": ["http"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "paths": {
    "/health": {
      "get": {
        "description": "Obtener el status del servidor para ver que todo ande bien",
        "summary": "Health",
        "tags": ["V1"],
        "operationId": "Health",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/api/v1/login": {
      "post": {
        "description": "Inicio de sesión en el SII",
        "summary": "Login",
        "tags": ["V1"],
        "operationId": "Login",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/api/v1/kardex": {
      "get": {
        "description": "Obtener el Kardex de calificaciones",
        "summary": "Kardex",
        "tags": ["V1"],
        "operationId": "Kardex",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8",
          "text/plain; charset=utf-8"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Kardex"
            },
            "examples": {
              "application/json; charset=utf-8": {
                "periodos": [
                  {
                    "periodo": "AGO-DIC",
                    "año": "2015",
                    "prom_semestral": "100",
                    "cred_aprovados": "4 / 4",
                    "calificaciones": [
                      {
                        "id": "AR9",
                        "materia": "INTELIGENCIA ARTIFICIAL",
                        "creditos": "4",
                        "calificacion": "100",
                        "evaluacion": "Ev.Ord.1ra",
                        "observaciones": ""
                      }
                    ]
                  }
                ],
                "alumno": {
                  "no_control": "12345678",
                  "nombre": "JUAN PEREZ",
                  "plan": "ISIC-2010-224",
                  "semestre": "13",
                  "carrera": "ING. SIST. COMP.",
                  "especialidad": "INTEGRACION DE TECNOLOGIAS"
                },
                "prom_aritmetico": "100",
                "cred_cursados": "4",
                "prom_certificado": "100",
                "cred_aprovados": "4"
              }
            },
            "headers": {
              "Vary": {
                "type": "string",
                "default": "Origin"
              },
              "Content-Length": {
                "type": "string",
                "default": "8618"
              },
              "Date": {
                "type": "string",
                "default": "Sat, 06 Nov 2021 00:40:08 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              },
              "Keep-Alive": {
                "type": "string",
                "default": "timeout=5"
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "type": "string",
              "default": ""
            },
            "examples": {
              "text/plain; charset=utf-8": "Unauthorized"
            },
            "headers": {
              "Vary": {
                "type": "string",
                "default": "Origin"
              },
              "Content-Length": {
                "type": "string",
                "default": "12"
              },
              "Date": {
                "type": "string",
                "default": "Sun, 07 Nov 2021 19:00:36 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              },
              "Keep-Alive": {
                "type": "string",
                "default": "timeout=5"
              }
            }
          }
        }
      }
    },
    "/api/v1/subject-progress": {
      "get": {
        "description": "Obtener el avance reticular del alumno",
        "summary": "Subject Progress",
        "tags": ["V1"],
        "operationId": "SubjectProgress",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8",
          "text/plain; charset=utf-8"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/SubjectProgress"
            },
            "headers": {
              "Vary": {
                "type": "string",
                "default": "Origin"
              },
              "Content-Length": {
                "type": "string",
                "default": "7054"
              },
              "Date": {
                "type": "string",
                "default": "Sun, 07 Nov 2021 19:04:11 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              },
              "Keep-Alive": {
                "type": "string",
                "default": "timeout=5"
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "type": "string",
              "default": ""
            },
            "examples": {
              "text/plain; charset=utf-8": "Unauthorized"
            },
            "headers": {
              "Vary": {
                "type": "string",
                "default": "Origin"
              },
              "Content-Length": {
                "type": "string",
                "default": "12"
              },
              "Date": {
                "type": "string",
                "default": "Sun, 07 Nov 2021 20:03:55 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              },
              "Keep-Alive": {
                "type": "string",
                "default": "timeout=5"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "LoginRequest": {
      "title": "LoginRequest",
      "example": {
        "usuario": "12590161",
        "contrasena": "8623"
      },
      "type": "object",
      "properties": {
        "usuario": {
          "type": "string"
        },
        "contrasena": {
          "type": "string"
        }
      },
      "required": ["usuario", "contrasena"]
    },
    "Kardex": {
      "title": "Kardex",
      "example": {
        "periodos": [
          {
            "periodo": "AGO-DIC",
            "año": "2015",
            "prom_semestral": "100",
            "cred_aprovados": "4 / 4",
            "calificaciones": [
              {
                "id": "AR9",
                "materia": "INTELIGENCIA ARTIFICIAL",
                "creditos": "4",
                "calificacion": "100",
                "evaluacion": "Ev.Ord.1ra",
                "observaciones": ""
              }
            ]
          }
        ],
        "alumno": {
          "no_control": "12345678",
          "nombre": "JUAN PEREZ",
          "plan": "ISIC-2010-224",
          "semestre": "13",
          "carrera": "ING. SIST. COMP.",
          "especialidad": "INTEGRACION DE TECNOLOGIAS"
        },
        "prom_aritmetico": "100",
        "cred_cursados": "4",
        "prom_certificado": "100",
        "cred_aprovados": "4"
      },
      "type": "object",
      "properties": {
        "periodos": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Periodo"
          }
        },
        "alumno": {
          "$ref": "#/definitions/Alumno"
        },
        "prom_aritmetico": {
          "type": "string"
        },
        "cred_cursados": {
          "type": "string"
        },
        "prom_certificado": {
          "type": "string"
        },
        "cred_aprovados": {
          "type": "string"
        }
      },
      "required": [
        "periodos",
        "alumno",
        "prom_aritmetico",
        "cred_cursados",
        "prom_certificado",
        "cred_aprovados"
      ]
    },
    "Periodo": {
      "title": "Periodo",
      "example": {
        "periodo": "AGO-DIC",
        "año": "2015",
        "prom_semestral": "100",
        "cred_aprovados": "4 / 4",
        "calificaciones": [
          {
            "id": "AR9",
            "materia": "INTELIGENCIA ARTIFICIAL",
            "creditos": "4",
            "calificacion": "100",
            "evaluacion": "Ev.Ord.1ra",
            "observaciones": ""
          }
        ]
      },
      "type": "object",
      "properties": {
        "periodo": {
          "type": "string"
        },
        "año": {
          "type": "string"
        },
        "prom_semestral": {
          "type": "string"
        },
        "cred_aprovados": {
          "type": "string"
        },
        "calificaciones": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Calificacione"
          }
        }
      },
      "required": [
        "periodo",
        "año",
        "prom_semestral",
        "cred_aprovados",
        "calificaciones"
      ]
    },
    "Calificacione": {
      "title": "Calificacione",
      "example": {
        "id": "AR9",
        "materia": "INTELIGENCIA ARTIFICIAL",
        "creditos": "4",
        "calificacion": "100",
        "evaluacion": "Ev.Ord.1ra",
        "observaciones": ""
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "materia": {
          "type": "string"
        },
        "creditos": {
          "type": "string"
        },
        "calificacion": {
          "type": "string"
        },
        "evaluacion": {
          "type": "string"
        },
        "observaciones": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "materia",
        "creditos",
        "calificacion",
        "evaluacion",
        "observaciones"
      ]
    },
    "Alumno": {
      "title": "Alumno",
      "example": {
        "no_control": "12345678",
        "nombre": "JUAN PEREZ",
        "plan": "ISIC-2010-224",
        "semestre": "13",
        "carrera": "ING. SIST. COMP.",
        "especialidad": "INTEGRACION DE TECNOLOGIAS"
      },
      "type": "object",
      "properties": {
        "no_control": {
          "type": "string"
        },
        "nombre": {
          "type": "string"
        },
        "plan": {
          "type": "string"
        },
        "semestre": {
          "type": "string"
        },
        "carrera": {
          "type": "string"
        },
        "especialidad": {
          "type": "string"
        }
      },
      "required": [
        "no_control",
        "nombre",
        "plan",
        "semestre",
        "carrera",
        "especialidad"
      ]
    },
    "SubjectProgress": {
      "title": "SubjectProgress",
      "type": "object",
      "properties": {
        "alumno": {
          "$ref": "#/definitions/Alumno1"
        },
        "progreso": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Progreso"
          }
        }
      },
      "required": ["alumno", "progreso"]
    },
    "Alumno1": {
      "title": "Alumno1",
      "example": {
        "no_control": "12345678",
        "nombre": "PEREZ JUAN",
        "semestre": "1",
        "periodo": "AGO-DIC/2021",
        "prom_acum": "100",
        "carrea": "INGENIERÍA EN SISTEMAS COMPUTACIONALES",
        "especialidad": "INTEGRACION DE TECNOLOGIAS"
      },
      "type": "object",
      "properties": {
        "no_control": {
          "type": "string"
        },
        "nombre": {
          "type": "string"
        },
        "semestre": {
          "type": "string"
        },
        "periodo": {
          "type": "string"
        },
        "prom_acum": {
          "type": "string"
        },
        "carrea": {
          "type": "string"
        },
        "especialidad": {
          "type": "string"
        }
      },
      "required": [
        "no_control",
        "nombre",
        "semestre",
        "periodo",
        "prom_acum",
        "carrea",
        "especialidad"
      ]
    },
    "Progreso": {
      "title": "Progreso",
      "example": {
        "id": "AR1",
        "materia": "CÁLCULO DIFERENCIAL",
        "calificacion": 100,
        "evaluacion": "01",
        "estatus": "verde",
        "semestre": 1
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "materia": {
          "type": "string"
        },
        "calificacion": {
          "type": "object"
        },
        "evaluacion": {
          "type": "string"
        },
        "estatus": {
          "type": "string"
        },
        "semestre": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "id",
        "materia",
        "calificacion",
        "evaluacion",
        "estatus",
        "semestre"
      ]
    }
  },
  "tags": [
    {
      "name": "V1",
      "description": ""
    }
  ]
}
